### ISSUE TITLE
Bağlaç olan de/da yazım hatası

### ISSUE THREAD

**Issue by mertingen** [suadev/turkish-microservice-architecture-book#3]
**Veritabanı Tabanı Tasarımı** konusu altında **Örnek Senaryo** başlığı altındaki aşağıdaki cümlede "de" ayrı olması gerekiyor.

> O zaman bizde ilişkisel veri tabanı kullanırız diye düşünebilirsiniz.

**Comment by suadev** [comment]
@mertingen çok teşekkürler :)
