### ISSUE TITLE
Gitbook yazım hatası.

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [suadev/turkish-microservice-architecture-book#4]
Tüm dökümanı incelemedim henüz ancak hızlı bir göz gezdirme sırasında;
Transaction Yönetimi -> ACID Prensipler -> Atomicity içerisinde "kısa" yerine "ksıa" olarak yazılmış, 

Dökümanı inceleyip farklı bir yazım hatası var mı bir ara bakacağım. Birde gitbook için düzeltme önerisi vs. gönderebileceğimiz bir yer varsa buradan issue yerine direk oradan da gönderebiliriz.

**Comment by suadev** [comment]
@SarperMUTLUBAY selam,

Yeni yazım hataları bulma ihtimaline karşı, bu maddeyi 1 süre bekletelim o halde, başka hatalar bulursan aşağıya yorum olarak ekleyebilir misin?

Desteğin için teşekkürler.

**Comment by SarperMUTLUBAY** [comment]
@suadev tabi ki, müsait olduğum ilk anda okuyarak bulduklarımı ekliyor olurum :)

**Comment by ustundag** [comment]
Selamlar, Öncelikle böyle derlenmiş Türkçe bir kaynak için çok teşekkür ederim. Umarım devamı gelir. 

Benim de denk geldiğim yazım hataları şunlar;
1- Veri Tabanı Tasarımı -> Big Data Uygulamalarında Kullanım -> unstructered, structered -> unstructured, structured

2- DDD ve Mikroservis Mimari -> Bounded Context’ler (Mikroservis’ler) Arası Veri Paylaşımı -> Contex’lerimizi -> Context’lerimizi

**Comment by SarperMUTLUBAY** [comment]
@ustundag hocam desteğin için teşekkürler, pandemi çıkışı iş yoğunluğundan dolayı bir türlü tam okuyup inceleyememiştim bende :)

**Comment by suadev** [comment]
@SarperMUTLUBAY  @ustundag  çok teşekkürker, tüm hataları düzeltip release çıktım şimdi.

Todo listte Github/Gitbook entegrasyonu maddesini eklemiştim. Onu halledince düzeltmeleri direkt Pull Request üzerinden alabileceğim, böylece katkı sağlayan herkes contributors olarak gözükecek. Ancak vakit ayırma noktasında sorun yaşıyorum biraz :)
