### ISSUE TITLE
Markdown lı versiyonu var mı?

### ISSUE THREAD

**Issue by ozkansen** [suadev/turkish-microservice-architecture-book#5]
Yazım hatalarının düzeltilmesi ve geliştirmeler için kitabın `markdown` ile yazılmış versiyonunu ekleyebilirmisin ?
Yazım hataları için `issue` açılması sağlıklı bir yöntem olmadığını düşünüyorum, kitap `markdown` formatında olursa düzeltmeleri `pull request` olarak gönderebiliriz.

Teşekkürler.

**Comment by suadev** [comment]
@ozkansen  selam,

Readme de ki Todo liste ilk iş olarak "Github / GitBook entegrasyonu" maddesini eklemiştim. Ancak henüz vakit ayıramadım, ne zaman bakabilirim onu da bilmiyorum.

Entegrasyon işini çözünceye dek issue üzerinden ilerleyebiliriz sanırım ki bu şekilde ileten arkadaşlar oldu.  Çok teşekkürler ilgin için.

**Comment by ozkansen** [comment]
Rica ederim, kitap için ayrıca teşekkürler.
