### ISSUE TITLE
Yazım yanlışı: trasnaction > transaction

### ISSUE THREAD

**Issue by ozgurg** [suadev/turkish-microservice-architecture-book#6]
Şu sayfadaki https://suadev.gitbook.io/turkish-microservices-book/microservice-mimarilerde-transaction-yoenetimi-nasil-yapilir ACID Prensipler > Durability bölümünde yazım yanlışı var.

<img width="835" alt="Screenshot_1" src="https://user-images.githubusercontent.com/6717356/100497194-c36e1d00-316a-11eb-83e3-eb1dd36ce175.png">

**Comment by suadev** [comment]
@ozgurg çok teşekkürler :)
